import React, { useState, useContext } from 'react';
import { UserContext } from '../context/UserContext';

const VerifyTOTP = ({ setShowVerifyTOTP, setUserContext }) => {
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [userContext] = useContext(UserContext);

  const verifyTOTP = async () => {
    try {
      const response = await fetch(`${process.env.REACT_APP_API_ENDPOINT}/users/verify-totp`, {
        method: 'POST',
        credentials: 'include',
        headers: {
          'Content-Type': 'application/json',
          "Authorization": `Bearer ${userContext.token}`,
        },
        body: JSON.stringify({ totp:code }),
      });

      if (!response.ok) {
        throw new Error('Invalid TOTP code. Please try again.');
      }

      const data = await response.json();
      if (data.success){
        setShowVerifyTOTP(false);
        setUserContext(oldValues => {
          return { ...oldValues, details: { ...oldValues.details, twoFactorEnabled: true } }});
      }else{
        setError('Invalid TOTP code. Please try again.');
      }
    } catch (error) {
      setError(error.message);
    }
  };

  return (
    <div>
      <h2>Enter TOTP Code</h2>
      <p>Please enter the 6-digit code generated by your authenticator app.</p>
      {error && <p>{error}</p>}
      <input type="text" value={code} onChange={e => setCode(e.target.value)} />
      <button onClick={verifyTOTP}>Verify TOTP Code</button>
    </div>
  );
};

export default VerifyTOTP;
